[package]
name = "rust_sqlite"
version = "0.1.0"
edition = "2018"

[dependencies]
csv = "1.1.3"
reqwest = { version = "0.11", features = ["blocking"] }
rusqlite = "0.26"

[lib]
name = "iris_functions"
path = "src/lib.rs"